version: "3.8"

services: 
  app:
    container_name: demo-backend
    restart: unless-stopped
    build: .
    ports: 
      - "3000:3000"
    depends_on: 
      - mongo
  
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo:4.0.4
    ports: 
      - "27017:27017"